/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import Project.Book;
import Project.DatabaseUtils;
import Project.Reservation;
import Project.User;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author User
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    private DefaultTableModel userModel;

    public UserFrame(User user) {
        initComponents();
        setResizable(false);
        setTitle("Readaroo | Admin");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        updateDashboardCounts();
        
        dashboardButton.setOpaque(true);
        viewAllBooksButton.setOpaque(true);
        reservedBooksButton.setOpaque(true);
        searchBooksButton.setOpaque(true);
        logoutButton.setOpaque(true);
    }

    //1 Dashboard
    private void updateDashboardCounts() {
        int totalBooks = DatabaseUtils.getTotalBooksCount();
        int totalUsers = DatabaseUtils.getTotalUsersCount();
        int totalReservations = DatabaseUtils.getTotalReservationsCount();

        totalBooksLabel.setText(String.valueOf(totalBooks));
        totalReservationsLabel.setText(String.valueOf(totalReservations));
    }

    //2 Search Function
    private void searchBook() {
        String searchText = searchBookField.getText();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a book title to search.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Book book = DatabaseUtils.getBookByTitle(searchText);
        if (book != null) {
            titleFieldS.setText(book.getTitle());
            authorFieldS.setText(book.getAuthor());
            availabilityCheckBoxS.setSelected(book.isAvailable());
        } else {
            JOptionPane.showMessageDialog(this, "Book not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    

    //3 Reserved Books Function
    private void loadReservedBooks() {
        DefaultTableModel model = (DefaultTableModel) reservedBooksTable.getModel();
        model.setRowCount(0); // Clear the table

        List<Reservation> reservations = DatabaseUtils.getAllReservations();
        for (Reservation reservation : reservations) {
            model.addRow(new Object[]{
                reservation.getReservationId(),
                reservation.getUserId(),
                reservation.getBookId(),
                reservation.getReservationDate(),
                reservation.getExpiryDate()
            });
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JLabel();
        viewAllBooksPanel = new javax.swing.JPanel();
        viewAllBooksButton = new javax.swing.JLabel();
        searchBooksPanel = new javax.swing.JPanel();
        searchBooksButton = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JLabel();
        reservedBooksPanel = new javax.swing.JPanel();
        reservedBooksButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalBooksLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        totalReservationsLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dashboardRefreshPanelButton = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        searchBookField = new javax.swing.JTextField();
        titleFieldS = new javax.swing.JTextField();
        searchBookButton = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        authorFieldS = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        availabilityCheckBoxS = new javax.swing.JCheckBox();
        userBorrowBook = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        userReserveBook = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reservedBooksTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(899, 656));
        setMinimumSize(new java.awt.Dimension(899, 656));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(212, 212, 212));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-user-male-48.png"))); // NOI18N
        jLabel2.setText("Hello User!");

        dashboardPanel.setBackground(new java.awt.Color(212, 212, 212));
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
        });

        dashboardButton.setBackground(new java.awt.Color(212, 212, 212));
        dashboardButton.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        dashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-dashboard-35.png"))); // NOI18N
        dashboardButton.setText(" Dashboard");
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        viewAllBooksPanel.setBackground(new java.awt.Color(212, 212, 212));
        viewAllBooksPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllBooksPanelMouseClicked(evt);
            }
        });

        viewAllBooksButton.setBackground(new java.awt.Color(212, 212, 212));
        viewAllBooksButton.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        viewAllBooksButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAllBooksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-view-all-35.png"))); // NOI18N
        viewAllBooksButton.setText(" View All Books");
        viewAllBooksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllBooksButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllBooksButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllBooksButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout viewAllBooksPanelLayout = new javax.swing.GroupLayout(viewAllBooksPanel);
        viewAllBooksPanel.setLayout(viewAllBooksPanelLayout);
        viewAllBooksPanelLayout.setHorizontalGroup(
            viewAllBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewAllBooksButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewAllBooksPanelLayout.setVerticalGroup(
            viewAllBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewAllBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        searchBooksPanel.setBackground(new java.awt.Color(212, 212, 212));
        searchBooksPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBooksPanelMouseClicked(evt);
            }
        });

        searchBooksButton.setBackground(new java.awt.Color(212, 212, 212));
        searchBooksButton.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        searchBooksButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBooksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-search-35.png"))); // NOI18N
        searchBooksButton.setText(" Search Books");
        searchBooksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBooksButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBooksButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBooksButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout searchBooksPanelLayout = new javax.swing.GroupLayout(searchBooksPanel);
        searchBooksPanel.setLayout(searchBooksPanelLayout);
        searchBooksPanelLayout.setHorizontalGroup(
            searchBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchBooksPanelLayout.setVerticalGroup(
            searchBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        logoutPanel.setBackground(new java.awt.Color(212, 212, 212));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(212, 212, 212));
        logoutButton.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 12)); // NOI18N
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-log-out-20.png"))); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        reservedBooksPanel.setBackground(new java.awt.Color(212, 212, 212));
        reservedBooksPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservedBooksPanelMouseClicked(evt);
            }
        });

        reservedBooksButton.setBackground(new java.awt.Color(212, 212, 212));
        reservedBooksButton.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        reservedBooksButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservedBooksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-reservedbooks-35 (2).png"))); // NOI18N
        reservedBooksButton.setText(" View Reserved Books");
        reservedBooksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservedBooksButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservedBooksButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservedBooksButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout reservedBooksPanelLayout = new javax.swing.GroupLayout(reservedBooksPanel);
        reservedBooksPanel.setLayout(reservedBooksPanelLayout);
        reservedBooksPanelLayout.setHorizontalGroup(
            reservedBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservedBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reservedBooksPanelLayout.setVerticalGroup(
            reservedBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservedBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewAllBooksPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchBooksPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservedBooksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewAllBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservedBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));

        jPanel12.setBackground(new java.awt.Color(242, 242, 242));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-books-100.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        jLabel1.setText("Total Books");

        totalBooksLabel.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 36)); // NOI18N
        totalBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBooksLabel.setText("69");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(totalBooksLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalBooksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(242, 242, 242));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-books-90.png"))); // NOI18N

        totalReservationsLabel.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 36)); // NOI18N
        totalReservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalReservationsLabel.setText("69");

        jLabel24.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        jLabel24.setText("Reserved Books");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalReservationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(53, 53, 53))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalReservationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(18, 18, 18))
        );

        jLabel17.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 30)); // NOI18N
        jLabel17.setText("USER DASHBOARD");

        dashboardRefreshPanelButton.setBackground(new java.awt.Color(242, 242, 242));
        dashboardRefreshPanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardRefreshPanelButtonMouseClicked(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-repeat-43.png"))); // NOI18N

        javax.swing.GroupLayout dashboardRefreshPanelButtonLayout = new javax.swing.GroupLayout(dashboardRefreshPanelButton);
        dashboardRefreshPanelButton.setLayout(dashboardRefreshPanelButtonLayout);
        dashboardRefreshPanelButtonLayout.setHorizontalGroup(
            dashboardRefreshPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardRefreshPanelButtonLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(47, 47, 47))
        );
        dashboardRefreshPanelButtonLayout.setVerticalGroup(
            dashboardRefreshPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardRefreshPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-walter-white-150.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 2, 18)); // NOI18N
        jLabel7.setText("\"More features to be ");

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 2, 18)); // NOI18N
        jLabel8.setText("added soon\" -Walter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(79, 79, 79)
                        .addComponent(dashboardRefreshPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(575, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(dashboardRefreshPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel5.setBackground(new java.awt.Color(242, 242, 242));

        jLabel12.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 24)); // NOI18N
        jLabel12.setText("View All Books");

        jTableBooks.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Title", "Author", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBooks);
        if (jTableBooks.getColumnModel().getColumnCount() > 0) {
            jTableBooks.getColumnModel().getColumn(0).setResizable(false);
            jTableBooks.getColumnModel().getColumn(1).setResizable(false);
            jTableBooks.getColumnModel().getColumn(2).setResizable(false);
            jTableBooks.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel12)))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setBackground(new java.awt.Color(242, 242, 242));

        searchBookField.setBackground(new java.awt.Color(212, 212, 212));

        titleFieldS.setBackground(new java.awt.Color(212, 212, 212));

        searchBookButton.setBackground(new java.awt.Color(212, 212, 212));
        searchBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBookButtonMouseClicked(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-search-35 (1).png"))); // NOI18N

        javax.swing.GroupLayout searchBookButtonLayout = new javax.swing.GroupLayout(searchBookButton);
        searchBookButton.setLayout(searchBookButtonLayout);
        searchBookButtonLayout.setHorizontalGroup(
            searchBookButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
            .addGroup(searchBookButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchBookButtonLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel33)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        searchBookButtonLayout.setVerticalGroup(
            searchBookButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(searchBookButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchBookButtonLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        authorFieldS.setBackground(new java.awt.Color(212, 212, 212));

        jLabel35.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18)); // NOI18N
        jLabel35.setText("Search Here:");

        jLabel36.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18)); // NOI18N
        jLabel36.setText("Author:");

        jLabel37.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18)); // NOI18N
        jLabel37.setText("Availability:");

        userBorrowBook.setBackground(new java.awt.Color(78, 175, 253));
        userBorrowBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userBorrowBook.setPreferredSize(new java.awt.Dimension(197, 53));
        userBorrowBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBorrowBookMouseClicked(evt);
            }
        });

        jLabel40.setBackground(new java.awt.Color(51, 51, 51));
        jLabel40.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        jLabel40.setText("Borrow this Book");

        javax.swing.GroupLayout userBorrowBookLayout = new javax.swing.GroupLayout(userBorrowBook);
        userBorrowBook.setLayout(userBorrowBookLayout);
        userBorrowBookLayout.setHorizontalGroup(
            userBorrowBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userBorrowBookLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(31, 31, 31))
        );
        userBorrowBookLayout.setVerticalGroup(
            userBorrowBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userBorrowBookLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel40)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        userReserveBook.setBackground(new java.awt.Color(78, 175, 253));
        userReserveBook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userReserveBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userReserveBookMouseClicked(evt);
            }
        });

        jLabel42.setBackground(new java.awt.Color(51, 51, 51));
        jLabel42.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Reserve this Book");

        javax.swing.GroupLayout userReserveBookLayout = new javax.swing.GroupLayout(userReserveBook);
        userReserveBook.setLayout(userReserveBookLayout);
        userReserveBookLayout.setHorizontalGroup(
            userReserveBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        userReserveBookLayout.setVerticalGroup(
            userReserveBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userReserveBookLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel42)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel43.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 18)); // NOI18N
        jLabel43.setText("Title:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(searchBookField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(searchBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleFieldS, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(availabilityCheckBoxS))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(userBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userReserveBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(authorFieldS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel35)))))
                .addContainerGap(623, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(searchBookField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleFieldS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorFieldS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel37))
                    .addComponent(availabilityCheckBoxS))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userReserveBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel7.setBackground(new java.awt.Color(242, 242, 242));

        jLabel14.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 24)); // NOI18N
        jLabel14.setText("Reserved Books");

        jScrollPane2.setBackground(new java.awt.Color(212, 212, 212));

        reservedBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "User ID", "Book ID", "Reservation Date", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reservedBooksTable);
        if (reservedBooksTable.getColumnModel().getColumnCount() > 0) {
            reservedBooksTable.getColumnModel().getColumn(0).setResizable(false);
            reservedBooksTable.getColumnModel().getColumn(1).setResizable(false);
            reservedBooksTable.getColumnModel().getColumn(2).setResizable(false);
            reservedBooksTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(379, 379, 379)))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -47, -1, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked
        // TODO add your handling code here:
//        jTabbedPane1.setSelectedIndex(0);
//        updateDashboardCounts();
    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void viewAllBooksPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBooksPanelMouseClicked
        // TODO add your handling code here:
//        jTabbedPane1.setSelectedIndex(1);
//
//        List<Book> books = DatabaseUtils.getAllBooks();
//        DefaultTableModel model = (DefaultTableModel) jTableBooks.getModel();
//        model.setRowCount(0); // Clear existing rows
//
//        for (Book book : books) {
//            model.addRow(new Object[]{book.getBookId(), book.getTitle(), book.getAuthor(), book.isAvailable()});
//        }
    }//GEN-LAST:event_viewAllBooksPanelMouseClicked

    private void searchBooksPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBooksPanelMouseClicked
        // TODO add your handling code here:
//        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_searchBooksPanelMouseClicked

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
//        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//    
//        if (response == JOptionPane.YES_OPTION) {           
//            LoginFrame loginFrame = new LoginFrame();
//            loginFrame.setVisible(true);          
//            this.setVisible(false);
//        }

    }//GEN-LAST:event_logoutPanelMouseClicked

    private void reservedBooksPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservedBooksPanelMouseClicked
        // TODO add your handling code here:
//        jTabbedPane1.setSelectedIndex(3);
//        loadReservedBooks();
    }//GEN-LAST:event_reservedBooksPanelMouseClicked

    private void dashboardRefreshPanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardRefreshPanelButtonMouseClicked
        // TODO add your handling code here:
        updateDashboardCounts();
    }//GEN-LAST:event_dashboardRefreshPanelButtonMouseClicked

    private void searchBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBookButtonMouseClicked
        // TODO add your handling code here:
        searchBook();
    }//GEN-LAST:event_searchBookButtonMouseClicked

    private void userBorrowBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBorrowBookMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "For assistance with borrowing a book, please reach out to the nearest library staff.", "Want to borrow a book?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_userBorrowBookMouseClicked

    private void userReserveBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userReserveBookMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "For assistance with book reservation, please reach out to the nearest library staff.", "Reserve a book?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_userReserveBookMouseClicked

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        updateDashboardCounts();
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void dashboardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseEntered
        // TODO add your handling code here:
        dashboardButton.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_dashboardButtonMouseEntered

    private void dashboardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseExited
        // TODO add your handling code here:
        dashboardButton.setBackground(new Color(212,212,212));
    }//GEN-LAST:event_dashboardButtonMouseExited

    private void viewAllBooksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBooksButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);

        List<Book> books = DatabaseUtils.getAllBooks();
        DefaultTableModel model = (DefaultTableModel) jTableBooks.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Book book : books) {
            model.addRow(new Object[]{book.getBookId(), book.getTitle(), book.getAuthor(), book.isAvailable()});
        }
    }//GEN-LAST:event_viewAllBooksButtonMouseClicked

    private void viewAllBooksButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBooksButtonMouseEntered
        // TODO add your handling code here:
        viewAllBooksButton.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_viewAllBooksButtonMouseEntered

    private void viewAllBooksButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBooksButtonMouseExited
        // TODO add your handling code here:
        viewAllBooksButton.setBackground(new Color(212,212,212));
    }//GEN-LAST:event_viewAllBooksButtonMouseExited

    private void searchBooksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBooksButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_searchBooksButtonMouseClicked

    private void searchBooksButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBooksButtonMouseEntered
        // TODO add your handling code here:
        searchBooksButton.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_searchBooksButtonMouseEntered

    private void searchBooksButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBooksButtonMouseExited
        // TODO add your handling code here:
        searchBooksButton.setBackground(new Color(212,212,212));
    }//GEN-LAST:event_searchBooksButtonMouseExited

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    
        if (response == JOptionPane.YES_OPTION) {           
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);          
            this.setVisible(false);
        }
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:
        logoutButton.setBackground(new Color(212,212,212));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void reservedBooksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservedBooksButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        loadReservedBooks();
    }//GEN-LAST:event_reservedBooksButtonMouseClicked

    private void reservedBooksButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservedBooksButtonMouseEntered
        // TODO add your handling code here:
        reservedBooksButton.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_reservedBooksButtonMouseEntered

    private void reservedBooksButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservedBooksButtonMouseExited
        // TODO add your handling code here:
        reservedBooksButton.setBackground(new Color(212,212,212));
    }//GEN-LAST:event_reservedBooksButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            User testUser = new User(1, "admin", "password123", "admin@gmail.com", true);
            
            public void run() {
                new UserFrame(testUser ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorFieldS;
    private javax.swing.JCheckBox availabilityCheckBoxS;
    private javax.swing.JLabel dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel dashboardRefreshPanelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel reservedBooksButton;
    private javax.swing.JPanel reservedBooksPanel;
    private javax.swing.JTable reservedBooksTable;
    private javax.swing.JPanel searchBookButton;
    private javax.swing.JTextField searchBookField;
    private javax.swing.JLabel searchBooksButton;
    private javax.swing.JPanel searchBooksPanel;
    private javax.swing.JTextField titleFieldS;
    private javax.swing.JLabel totalBooksLabel;
    private javax.swing.JLabel totalReservationsLabel;
    private javax.swing.JPanel userBorrowBook;
    private javax.swing.JPanel userReserveBook;
    private javax.swing.JLabel viewAllBooksButton;
    private javax.swing.JPanel viewAllBooksPanel;
    // End of variables declaration//GEN-END:variables
}
